all:
  children:
    hetzner:
      hosts:
        server01.devluchs.de:
        server02.devluchs.de:
        server03.devluchs.de:
        server04.devluchs.de:
    nameservers:
      hosts:
        server01.devluchs.de:
        server02.devluchs.de:
    webservers:
      hosts:
        server01.devluchs.de:
        server02.devluchs.de:
        server03.devluchs.de:
