---
ansible_user: root
ansible_ssh_private_key_file: /home/nobara/Portable/DataStore/Hetzner/HetznerCloudSSH
certbot_email: webmaster@devluchs.de
certbot_domains:
  - devluchs.de
  - www.devluchs.de
certbot_primary_host: server01.devluchs.de
